# Generated by Django 6.0.2 on 2026-02-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='post.status'),
            preserve_default=False,
        ),
    ]
